from schemas.response import ReviewResult

SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}

TYPE_EMOJI = {
    "bug": "🐛",
    "security": "🔒",
    "performance": "⚡",
    "smell": "🧹",
    "style": "✏️",
}

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]

def severity_emoji(severity: str) -> str:
    return SEVERITY_EMOJI.get(severity, "⚪")

def type_emoji(issue_type: str) -> str:
    return TYPE_EMOJI.get(issue_type, "❓")

def score_bar(score: int) -> str:
    filled = round(score / 10)
    return "█" * filled + "░" * (10 - filled)

def review_to_markdown(result: ReviewResult) -> str:
    lines: list[str] = []

    lines.append("# 🔍 Revvy Code Review")
    lines.append("")
    lines.append(f"**Review ID:** `{result.review_id}`")
    lines.append(f"**Timestamp:** {result.reviewed_at.strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"**Language:** {result.language}")
    if result.filename:
        lines.append(f"**File:** `{result.filename}`")
    lines.append("")

    lines.append("## 📊 Score")
    lines.append("")
    lines.append(f"`{score_bar(result.score)}` **{result.score}/100** — {result.verdict.upper()}")
    lines.append("")

    lines.append("## 📝 Summary")
    lines.append("")
    lines.append(result.summary)
    lines.append("")

    if result.issues:
        lines.append("## 🚨 Issues")
        lines.append("")

        issues_by_severity: dict[str, list] = {s: [] for s in SEVERITY_ORDER}
        for issue in result.issues:
            issues_by_severity.setdefault(issue.severity, []).append(issue)

        for severity in SEVERITY_ORDER:
            group = issues_by_severity.get(severity, [])
            if not group:
                continue

            lines.append(f"### {severity_emoji(severity)} {severity.upper()}")
            lines.append("")

            for issue in group:
                lines.append(f"#### {type_emoji(issue.type)} {severity_emoji(issue.severity)} {issue.title}")

                if issue.line_start is not None:
                    if issue.line_end is not None and issue.line_end != issue.line_start:
                        lines.append(f"📍 Lines {issue.line_start}–{issue.line_end}")
                    else:
                        lines.append(f"📍 Line {issue.line_start}")

                lines.append("")
                lines.append(issue.description)
                lines.append("")
                lines.append(f"> **Suggestion:** {issue.suggestion}")
                lines.append("")

    lines.append("---")
    lines.append("*Generated by Revvy*")

    return "\n".join(lines)
